server:
  port: 8080

spring:
  datasource:
    username: root
    password: 2241260269zjw
    url: jdbc:mysql://localhost:3306/mysql_platform_db1?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource



#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml


